import "@radix-ui/themes/styles.css";
import "./theme-config.css";
import "./globals.css";
import type { Metadata } from "next";
import { Theme } from "@radix-ui/themes";
import { Inter } from "next/font/google";
import DarkModeContext from "./DarkModeContext";
import NavBar from "./NavBar";

const inter = Inter({
  subsets: ["latin"],
  // display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Next Preference Reset",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <DarkModeContext>
          <Theme accentColor="iris" radius="none">
            <NavBar />
            <main className="px-5">{children}</main>
          </Theme>
        </DarkModeContext>
      </body>
    </html>
  );
}
